In [24]:
import jax
import jax.numpy as jnp
import mediapy
import numpy as np
from PIL import Image
import videoprism.models as vp

MODEL_NAME = 'videoprism_public_v1_base_hf'
NUM_FRAMES = 16
FRAME_SIZE = 288

flax_model = vp.get_model(MODEL_NAME)  #? step 1 get model is in models
loaded_state = vp.load_pretrained_weights(MODEL_NAME)    #? step 4  need to see the type of this obj
print(type(loaded_state))

<class 'flax.core.frozen_dict.FrozenDict'>


In [2]:
loaded_state

FrozenDict({
    params: {
        patch_projection: {
            linear: {
                bias: array([-6.20352337e-03, -1.43539775e-02, -1.89917549e-01,  1.00830102e+00,
                       -1.56504869e-01, -3.08199245e-02,  1.12415545e-01,  5.52925840e-02,
                        1.18033625e-01, -3.95718543e-03, -2.48173997e-02,  3.57118323e-02,
                       -5.30083617e-03, -1.03991712e-02, -3.28369811e-02,  2.22367067e-02,
                       -2.46783584e-01, -4.24713222e-03, -3.30852568e-02,  3.41785774e-02,
                       -1.25858712e-03, -5.50246472e-03, -1.22910400e-03, -3.57640460e-02,
                       -9.32076573e-02, -3.93759878e-03,  5.67617535e-04,  1.18225801e-03,
                       -1.28023282e-01, -4.48273495e-03,  2.47205212e-03, -3.78008257e-03,
                       -8.84351358e-02, -4.79604444e-03, -9.10369903e-02, -2.20087394e-02,
                       -1.04983523e-03, -1.10497288e-02,  5.69587052e-02,  7.04188505e-03,
       

In [25]:
from flax.core import FrozenDict

# Assuming `loaded_state` is a FrozenDict
if isinstance(loaded_state, FrozenDict):
    # Convert to a regular dictionary for inspection
    params_dict = loaded_state.unfreeze()
    
    # Print the keys and structure
    for key, value in params_dict.items():
        print(f"Key: {key}, Value Type: {type(value)}")
        
    # Optionally, inspect specific parameters
    print("First layer parameters:", params_dict.get(f'{key}', 'Not found'))
else:
    print("loaded_state is not a FrozenDict")

Key: params, Value Type: <class 'dict'>
First layer parameters: {'patch_projection': {'linear': {'bias': array([-6.20352337e-03, -1.43539775e-02, -1.89917549e-01,  1.00830102e+00,
       -1.56504869e-01, -3.08199245e-02,  1.12415545e-01,  5.52925840e-02,
        1.18033625e-01, -3.95718543e-03, -2.48173997e-02,  3.57118323e-02,
       -5.30083617e-03, -1.03991712e-02, -3.28369811e-02,  2.22367067e-02,
       -2.46783584e-01, -4.24713222e-03, -3.30852568e-02,  3.41785774e-02,
       -1.25858712e-03, -5.50246472e-03, -1.22910400e-03, -3.57640460e-02,
       -9.32076573e-02, -3.93759878e-03,  5.67617535e-04,  1.18225801e-03,
       -1.28023282e-01, -4.48273495e-03,  2.47205212e-03, -3.78008257e-03,
       -8.84351358e-02, -4.79604444e-03, -9.10369903e-02, -2.20087394e-02,
       -1.04983523e-03, -1.10497288e-02,  5.69587052e-02,  7.04188505e-03,
       -7.70751573e-03, -5.01443185e-02, -6.43940985e-01, -9.71446745e-03,
       -2.51517422e-03, -3.09577491e-03,  1.58595487e-01,  9.70437080e

In [9]:
params_dict

{'params': array({'patch_projection': {'linear': {'bias': array([-6.20352337e-03, -1.43539775e-02, -1.89917549e-01,  1.00830102e+00,
        -1.56504869e-01, -3.08199245e-02,  1.12415545e-01,  5.52925840e-02,
         1.18033625e-01, -3.95718543e-03, -2.48173997e-02,  3.57118323e-02,
        -5.30083617e-03, -1.03991712e-02, -3.28369811e-02,  2.22367067e-02,
        -2.46783584e-01, -4.24713222e-03, -3.30852568e-02,  3.41785774e-02,
        -1.25858712e-03, -5.50246472e-03, -1.22910400e-03, -3.57640460e-02,
        -9.32076573e-02, -3.93759878e-03,  5.67617535e-04,  1.18225801e-03,
        -1.28023282e-01, -4.48273495e-03,  2.47205212e-03, -3.78008257e-03,
        -8.84351358e-02, -4.79604444e-03, -9.10369903e-02, -2.20087394e-02,
        -1.04983523e-03, -1.10497288e-02,  5.69587052e-02,  7.04188505e-03,
        -7.70751573e-03, -5.01443185e-02, -6.43940985e-01, -9.71446745e-03,
        -2.51517422e-03, -3.09577491e-03,  1.58595487e-01,  9.70437080e-02,
        -1.02890772e-03, -3.094

In [14]:
import jax.numpy as jnp

jnp.array([1,2,3]).__array__()


array([1, 2, 3], dtype=int32)

In [28]:
import numpy as np
link = "https://huggingface.co/google/videoprism-base-f16r288/resolve/main/flax_base_f16r288_repeated.npz?download=true"

ckpt = np.load(link)




FileNotFoundError: [Errno 2] No such file or directory: 'https://huggingface.co/google/videoprism-base-f16r288/resolve/main/flax_base_f16r288_repeated.npz?download=true'

In [ ]:
from safetensors.flax import save_file
save_file(params_dict, f'videoprism-base-f16r288.safetensors')  #? step 5 save the model weights in safetensors format

In [ ]:
params_dict

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [26]:
params = params_dict['params']
keys = params.keys()
keys

dict_keys(['patch_projection', 'spatial_encoder', 'spatial_ln', 'spatial_pos_emb', 'temporal_encoder', 'temporal_ln', 'temporal_pos_emb'])

In [27]:
params

{'patch_projection': {'linear': {'bias': array([-6.20352337e-03, -1.43539775e-02, -1.89917549e-01,  1.00830102e+00,
          -1.56504869e-01, -3.08199245e-02,  1.12415545e-01,  5.52925840e-02,
           1.18033625e-01, -3.95718543e-03, -2.48173997e-02,  3.57118323e-02,
          -5.30083617e-03, -1.03991712e-02, -3.28369811e-02,  2.22367067e-02,
          -2.46783584e-01, -4.24713222e-03, -3.30852568e-02,  3.41785774e-02,
          -1.25858712e-03, -5.50246472e-03, -1.22910400e-03, -3.57640460e-02,
          -9.32076573e-02, -3.93759878e-03,  5.67617535e-04,  1.18225801e-03,
          -1.28023282e-01, -4.48273495e-03,  2.47205212e-03, -3.78008257e-03,
          -8.84351358e-02, -4.79604444e-03, -9.10369903e-02, -2.20087394e-02,
          -1.04983523e-03, -1.10497288e-02,  5.69587052e-02,  7.04188505e-03,
          -7.70751573e-03, -5.01443185e-02, -6.43940985e-01, -9.71446745e-03,
          -2.51517422e-03, -3.09577491e-03,  1.58595487e-01,  9.70437080e-02,
          -1.02890772e-03,

In [22]:
type(params['patch_projection']['linear']['kernel'])

numpy.ndarray

In [18]:
type(params_dict)

dict

In [23]:

import numpy as np

def tree(obj):
    if isinstance(obj, dict):
        return {k: tree(v) for k, v in obj.items()}

    elif isinstance(obj, (list, tuple)):
        return type(obj)(tree(v) for v in obj)

    elif isinstance(obj, np.ndarray):
        return obj.shape
    else:
        return obj

In [24]:
tree(params_dict)

{'params': {'patch_projection': {'linear': {'bias': (768,),
    'kernel': (972, 768)}},
  'spatial_encoder': {'transformers_stack': {'x_layers': {'ff_layer': {'ffn_layer1': {'linear': {'bias': (12,
         3072),
        'kernel': (12, 768, 3072)}},
      'ffn_layer2': {'linear': {'bias': (12, 768), 'kernel': (12, 3072, 768)}},
      'layer_norm': {'bias': (12, 768), 'scale': (12, 768)}},
     'layer_norm': {'bias': (12, 768), 'scale': (12, 768)},
     'self_attention': {'key': {'b': (12, 12, 64), 'w': (12, 768, 12, 64)},
      'post': {'b': (12, 768), 'w': (12, 768, 12, 64)},
      'query': {'b': (12, 12, 64), 'w': (12, 768, 12, 64)},
      'value': {'b': (12, 12, 64), 'w': (12, 768, 12, 64)}}}}},
  'spatial_ln': {'bias': (768,), 'scale': (768,)},
  'spatial_pos_emb': {'emb_var': (256, 768)},
  'temporal_encoder': {'transformers_stack': {'x_layers': {'ff_layer': {'ffn_layer1': {'linear': {'bias': (4,
         3072),
        'kernel': (4, 768, 3072)}},
      'ffn_layer2': {'linear': {

In [ ]:
params_dict = loaded_state.unfreeze()
params_dict

In [4]:
print("yo")

yo


In [1]:
spaghetti_path = '/teamspace/studios/this_studio/.cache/huggingface/hub/datasets--hf-internal-testing--spaghetti-video/snapshots/2702354ff5c46c409dceae8abcc2cef2c3efc76a/eating_spaghetti_32_frames.npy'

In [2]:
import jax
import jax.numpy as jnp
import mediapy
import numpy as np
from PIL import Image
import videoprism.models as vp


def read_and_preprocess_video(
    filename: str, target_num_frames: int, target_frame_size: tuple[int, int]
):
  """Reads and preprocesses a video."""
  try:
    frames = mediapy.read_video(filename)
  except:
    frames = np.array(np.load(filename))
  # Sample to target number of frames.
  frame_indices = np.linspace(
      0, len(frames), num=target_num_frames, endpoint=False, dtype=np.int32
  )
  frames = np.array([frames[i] for i in frame_indices])

  # Resize to target size.
  original_height, original_width = frames.shape[-3:-1]
  target_height, target_width = target_frame_size
#   assert (
#       original_height * target_width == original_width * target_height
#   ), 'Currently does not support aspect ratio mismatch.'
  frames = mediapy.resize_video(frames, shape=target_frame_size)

  # Normalize pixel values to [0.0, 1.0].
  frames = mediapy.to_float01(frames)

  return frames

  
MODEL_NAME = 'videoprism_public_v1_large_hf'

# 'videoprism_public_v1_base': videoprism_v1_base,
# 'videoprism_public_v1_large': videoprism_v1_large,
# 'videoprism_public_v1_base_hf': videoprism_v1_base,
# 'videoprism_public_v1_large_hf': videoprism_v1_large,

NUM_FRAMES = 8
FRAME_SIZE = 288

flax_model = vp.get_model(MODEL_NAME)  #? step 1 get model is in models
loaded_state = vp.load_pretrained_weights(MODEL_NAME)    #? step 4  flax.core.frozen_dict.FrozenDict
print(type(loaded_state))

# @jax.jit
def forward_fn(inputs, train=False):
  return flax_model.apply(loaded_state, inputs, train=train)   #? inputs is a jnp array of shape (B, 16, 288, 288, 3)

VIDEO_FILE_PATH = (
    './videoprism/assets/water_bottle_drumming.mp4'
)
frames = read_and_preprocess_video(
    VIDEO_FILE_PATH,
    target_num_frames=NUM_FRAMES,  #? 16
    target_frame_size=[FRAME_SIZE, FRAME_SIZE], #? 288
)
print("frames read", )
#mediapy.show_video(frames, fps=6.0)

frames = jnp.asarray(frames[None, ...])  # Add batch dimension.
#print(f'Input shape: {frames.shape}and some values: {frames[0, 0, 0, 0, :]}')  #? step 3 convert to jnp array and add batch dimension
print(f"{frames[0,0,:3,:3,0]=}")
with jax.disable_jit():
    embeddings, _ = forward_fn(frames)   #? step 5 use the aply method to invoke the __call__ of FactorizedEncoder
print(f'Encoded embedding shape: {embeddings.shape}, and some values: {embeddings[0, :3, :3]}')  #? step 6 get the embeddings and print the shape and some values


<class 'flax.core.frozen_dict.FrozenDict'>
frames read
frames[0,0,:3,:3,0]=Array([[0.68235296, 0.2627451 , 0.25882354],
       [0.7607843 , 0.3019608 , 0.22352941],
       [0.8039216 , 0.4       , 0.22745098]], dtype=float32)
patches.shape=(8, 256, 1024), [[-0.26194355 -0.12460318 -0.24397591]
 [-0.29950485  0.04141423 -0.00900379]
 [-0.21118599  0.3313682   0.04797216]]
after norm: [[ 0.08220339  0.00567213 -0.18106323]
 [-0.01337895  0.10139874 -0.04364363]
 [ 0.06671576  0.20870823 -0.05103884]]
after attention, before residual and before ffn: [[ 0.20860109  0.12911934 -0.02863857]
 [ 0.17246601  0.13040453 -0.02217479]
 [ 0.11756586  0.06699194 -0.00144264]]
after residual and before ffn: [[-0.05334246  0.00451615 -0.27261448]
 [-0.12703884  0.17181876 -0.03117858]
 [-0.09362014  0.39836013  0.04652952]]
after ffn, before final norm: [[-1.2829823  -5.2027993  -0.86707765]
 [-2.190866   -2.5461636  -0.7590506 ]
 [-5.1275196  -2.2589254   0.09337451]]
after norm: [[-0.19483307 -0.873

# LVT models

In [ ]:
import jax
import jax.numpy as jnp
from videoprism import models as vp
import mediapy
import numpy as np
from PIL import Image

MODEL_NAME = 'videoprism_lvt_public_v1_base'  # @param ['videoprism_lvt_public_v1_base', 'videoprism_lvt_public_v1_large'] {allow-input: false}
NUM_FRAMES = 16
FRAME_SIZE = 288

flax_model = vp.get_model(MODEL_NAME)
loaded_state = vp.load_pretrained_weights(MODEL_NAME)
text_tokenizer = vp.load_text_tokenizer('c4_en')


@jax.jit
def forward_fn(inputs, text_token_ids, text_paddings, train=False):
  return flax_model.apply(
      loaded_state,
      inputs,
      text_token_ids,
      text_paddings,
      train=train,
  )

def read_and_preprocess_video(
    filename: str, target_num_frames: int, target_frame_size: tuple[int, int]
):
  """Reads and preprocesses a video."""
  try:
    frames = mediapy.read_video(filename)
  except:
    frames = np.array(np.load(filename))
  # Sample to target number of frames.
  frame_indices = np.linspace(
      0, len(frames), num=target_num_frames, endpoint=False, dtype=np.int32
  )
  frames = np.array([frames[i] for i in frame_indices])

  # Resize to target size.
  original_height, original_width = frames.shape[-3:-1]
  target_height, target_width = target_frame_size
#   assert (
#       original_height * target_width == original_width * target_height
#   ), 'Currently does not support aspect ratio mismatch.'
  frames = mediapy.resize_video(frames, shape=target_frame_size)

  # Normalize pixel values to [0.0, 1.0].
  frames = mediapy.to_float01(frames)

  return frames

VIDEO_FILE_PATH = (
    './videoprism/assets/water_bottle_drumming.mp4'
)

frames = read_and_preprocess_video(
    VIDEO_FILE_PATH,
    target_num_frames=NUM_FRAMES,
    target_frame_size=[FRAME_SIZE, FRAME_SIZE],
)
frames = jnp.asarray(frames[None, ...])  # Add batch dimension. 

TEXT_QUERY_CSV = 'playing drums,sitting,playing flute,playing at playground,concert'  # @param {type: "string"}
PROMPT_TEMPLATE = 'a video of {}.'

text_queries = TEXT_QUERY_CSV.split(',')
text_queries = [PROMPT_TEMPLATE.format(t) for t in text_queries]
text_ids, text_paddings = vp.tokenize_texts(text_tokenizer, text_queries) # step 1

video_embeddings, text_embeddings, _ = forward_fn(
    frames, text_ids, text_paddings)

patches.shape=(16, 256, 768), Traced<ShapedArray(float32[3,3])>with<DynamicJaxprTrace(level=1/0)>
spatial_encoder features.shape=(16, 256, 768), Traced<ShapedArray(float32[3,3])>with<DynamicJaxprTrace(level=1/0)>
spatial_encoder ln features.shape=(16, 256, 768), Traced<ShapedArray(float32[3,3])>with<DynamicJaxprTrace(level=1/0)>
temporal embedding features.shape=(256, 16, 768), Traced<ShapedArray(float32[3,3])>with<DynamicJaxprTrace(level=1/0)>
temporal_encoder features.shape=(256, 16, 768), Traced<ShapedArray(float32[3,3])>with<DynamicJaxprTrace(level=1/0)>
temporal_encoder ln features.shape=(256, 16, 768), Traced<ShapedArray(float32[3,3])>with<DynamicJaxprTrace(level=1/0)>
final features.shape=(1, 4096, 768), Traced<ShapedArray(float32[3,3])>with<DynamicJaxprTrace(level=1/0)>
after norm: [[-0.18466176 -0.03877358 -0.07794335]
 [-0.04724635 -0.19140227 -0.00291522]
 [ 0.04022204  0.23409425 -0.02656671]]
after attention, before residual and before ffn: [[ 0.01565626  0.02001801  0.136

In [14]:
text_tokenizer.vocab_size

32000

In [15]:
text_ids, text_paddings


(array([[  262,   266,   768,   267,  1376, 14293,   259,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [  262,   266,   768,   267,  2865,   259,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,    

In [16]:
text_queries

['a video of playing drums.',
 'a video of sitting.',
 'a video of playing flute.',
 'a video of playing at playground.',
 'a video of concert.']

In [17]:
len(text_ids[0])

64